config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'home/index'
  get 'dashboard/index'
  get 'dashboard' => 'dashboard#index'
  get 'settings' => 'dashboard#settings'
  get 'decide' => 'dashboard#decide'
  get 'community' => 'dashboard#community'
  get '/transactions/import/:statement', to: 'transactions#import'
  resources :transactions

  root 'home#index'

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

  belongs_to :user


  validates :time,              presence: true
  validates :amount,            presence: true
  validates :transaction_type,  presence: true
  validates :name,              presence: true

  def credit?
    self.amount > 0
  end

  def debit?
    !credit?
  end

  def debit_card_transaction?
    self.transaction_type.downcase == 'debit card transaction'
  end

  def saving_amount
    return 0 unless debit_card_transaction?
    pennies = 100 - self.amount.to_s[-2, 2].to_i
    pennies
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  has_many :transactions

  before_validation(on: :create) { ensure_authentication_token }
  before_validation { ensure_user_id }

  validates :username, uniqueness: true

  #---------------------------------------------------------------------------
  private

  def ensure_user_id
    self.username ||= self.id.to_s
  end

  def ensure_authentication_token
    self.authentication_token ||= generate_authentication_token
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    dashboard_path
  end

  def after_sign_out_path_for(user)
    root_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate_user!

  def index
    @date_1 = Time.now
    begin
      @date_1 = Time.parse(params[:date_1])
    rescue
      puts 'could not parse date_1'
    end
    @date_2 = Time.now - 60.days
    begin
      @date_2 = Time.parse(params[:date_2])
    rescue
      puts 'could not parse date_2'
    end
    date_range = [@date_1, @date_2].sort
    @date_1 = date_range.first
    @date_2 = date_range.last
    @days = (@date_2 - @date_1).to_i / (24 * 60 * 60)

    @transactions = current_user.transactions.where('time > ?', @date_1).where('time < ?', @date_2).order(time: :desc)
    @savings = 0
    @chart_data = []
    @transactions.each do |transaction|
      @savings += transaction.saving_amount
      @chart_data << @savings / 100.0 # if @savings > 0.00
    end
  end

  def community

  end

  def donations

  end

  def settings
    @user = current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render layout: 'public'
  end
end

app/controllers/transactions_controller.rb
require 'JSON'

class TransactionsController < ApplicationController

  before_action :authenticate_user!

  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  def index
    @transactions = current_user.transactions.order(time: :desc)
  end

  # GET /transactions/1
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @transaction.user = current_user
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = current_user

    if @transaction.save
      redirect_to @transaction, notice: 'Transaction was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /transactions/1
  def update
    if @transaction.update(transaction_params)
      redirect_to @transaction, notice: 'Transaction was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /transactions/1
  def destroy
    @transaction.destroy
    redirect_to transactions_url, notice: 'Transaction was successfully destroyed.'
  end

  def import
    source_file = params[:statement]
    if source_file
      source_file = "#{source_file}.json" unless source_file =~ /.json$/
      TransactionsController.import_statement("DATA/#{source_file}")
    end
    redirect_to dashboard_path
  end

  def self.import_statement(json_file)
    return unless json_file && json_file.is_a?(String)
    return unless File.exist? json_file
    hash = JSON.parse(File.read(json_file))

    user_id = hash['user_id'].to_i
    raise "User with ID #{user_id} not found" unless User.exists?(user_id)
    user = User.find(user_id)
    hash['transactions'].each do |transaction|
      time = transaction['date']
      name = transaction['payee']
      amount = (transaction['amount'] * 100).to_i
      type = transaction['type']
      import_transaction(user, time, name, amount, type)
    end

    user.save
    puts "Added #{user.transactions.count} transactions"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def transaction_params
      params.require(:transaction).permit(:transaction_type, :time, :name, :amount)
    end

  def self.import_transaction(user, time, name, amount, type)
    transaction = user.transactions.where(time: time).first
    unless transaction
      transaction = Transaction.create(time: time, amount: amount, transaction_type: type, name: name)
      puts "Created transaction for #{user.email} #{time} #{name.ljust(30)} #{amount}"
    end
    user.transactions << transaction
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/dashboard/community.html.erb
<div id="community">
  <div id="charities" class="body-box" style="width: 100%;">
    <div class="charity">
      <p class="charity_name">Action Medical Research</p>
      <p class="charity_amount">€2,562</p>
      <p class="charity_desc">
        Action Medical Research began in 1952 as the National Fund for Poliomyelitis Research, with the aim of stopping the feared polio virus.
      </p>
      <%= image_tag 'charity/action.png' %>
    </div>

    <div class="charity">
      <p class="charity_name">Water Aid</p>
      <p class="charity_amount">€1,798</p>
      <p class="charity_desc">
        We transform lives by improving access to safe water, hygiene and sanitation in the world’s poorest communities since 1984.
      </p>
      <%= image_tag 'charity/water_aid.png' %>
    </div>

    <div class="charity">
      <p class="charity_name">Mary’s Meals</p>
      <p class="charity_amount">€1,263</p>
      <p class="charity_desc">
        Mary’s Meals began in 2002 as a one-off school feeding programme. Today we provide daily life changing meals to over 989,000 hungry children.
      </p>
      <%= image_tag 'charity/marys_meals.png' %>
    </div>

    <div class="charity">
      <p class="charity_name">Simon Community</p>
      <p class="charity_amount">€806</p>
      <p class="charity_desc">
        Simon Community Northern Ireland is your local homelessness charity. We work hard to ensure that anyone who is homeless or at risk of losing their home gets the support they need.
      </p>
      <%= image_tag 'charity/simon_community.png' %>
    </div>

    <div class="charity">
      <p class="charity_name">Assisi Animal Sanctuary</p>
      <p class="charity_amount"> €132 </p>
      <p class="charity_desc">
        Assisi Animal Sanctuary is Northern Ireland's largest independent animal welfare charity providing shelter for up to 200 companion animals - cats, dogs and rabbits.
      </p>
      <%= image_tag 'charity/assisi.png' %>
    </div>
  </div>

</div>

app/views/dashboard/decide.html.erb
<div id="decide">
  <div id="last-month-saved" class="body-box">
    Saved Last Month <span style="display: block; font-weight: bold;padding-top: 16px;">£12.11</span>
  </div>

  <div id="decision-links">
    <div id="savings-goal-link" class="body-box">
      Savings Goals
    </div>

    <div id="charity-link" class="body-box">
      Charity
    </div>

    <div id="do-nothing-link" class="body-box">
      Save Longer
    </div>
  </div>

  <div id="decision-descriptions" class="body-box">
    
    <div id="saving-goals">
      <div class="goal">
        <h2>Holidays</h2>
        <%= image_tag 'goals/holidays.jpg' %>
      </div>
      <div class="goal">
        <h2>Present for Mum</h2>
        <%= image_tag 'goals/present.jpg' %>
      </div>
      <div class="goal">
        <h2>Vespa</h2>
        <%= image_tag 'goals/rossa.png' %>
      </div>
    </div>
    
    
    <div id="charities" style="display: none;">
      <div class="charity">
        <p class="charity_name">Action Medical Research</p>
        <p class="charity_amount">€1000.00</p>
        <p class="charity_desc">
          Action Medical Research began in 1952 as the National Fund for Poliomyelitis Research, with the aim of stopping the feared polio virus.
        </p>
        <%= image_tag 'charity/action.png' %>
      </div>

      <div class="charity">
        <p class="charity_name">Water Aid</p>
        <p class="charity_amount">€1000.00</p>
        <p class="charity_desc">
          We transform lives by improving access to safe water, hygiene and sanitation in the world’s poorest communities since 1984.
        </p>
        <%= image_tag 'charity/water_aid.png' %>
      </div>

      <div class="charity">
        <p class="charity_name">Mary’s Meals</p>
        <p class="charity_amount">€1000.00</p>
        <p class="charity_desc">
          Mary’s Meals began in 2002 as a one-off school feeding programme. Today we provide daily life changing meals to over 989,000 hungry children.
        </p>
        <%= image_tag 'charity/marys_meals.png' %>
      </div>

      <div class="charity">
        <p class="charity_name">Simon Community</p>
        <p class="charity_amount">€1000.00</p>
        <p class="charity_desc">
          Simon Community Northern Ireland is your local homelessness charity. We work hard to ensure that anyone who is homeless or at risk of losing their home gets the support they need.
        </p>
        <%= image_tag 'charity/simon_community.png' %>
      </div>

      <div class="charity">
        <p class="charity_name">Assisi Animal Sanctuary</p>
        <p class="charity_amount">
          €1000.00
        </p>
        <p class="charity_desc">
          Assisi Animal Sanctuary is Northern Ireland's largest independent animal welfare charity providing shelter for up to 200 companion animals - cats, dogs and rabbits.
        </p>
        <%= image_tag 'charity/assisi.png' %>
      </div>
    </div>
    
    
    <div id="do-nothing" style="display: none;">
      Continue saving and next month you will have even more to decide for!
    </div>
  </div>
</div>

<script>
  $('#savings-goal-link').click(function() {
      $('#saving-goals').show();
      $('#charities').hide();
      $('#do-nothing').hide();
  });

  $('#charity-link').click(function() {
      $('#saving-goals').hide();
      $('#charities').show();
      $('#do-nothing').hide();
  });

  $('#do-nothing-link').click(function() {
      $('#saving-goals').hide();
      $('#charities').hide();
      $('#do-nothing').show();
  });
</script>

app/views/dashboard/index.html.erb
<!--h1>Dashboard</h1-->

<div id="dashboard">

  <div id="my-savings" class="body-box">
    <div id="my-savings-stats">
      <p>My savings</p>
      <p>
        <%= link_to "£#{'%.2f' % (@savings / 100.0)}", decide_path %>
      </p>

      <!--p style="font-weight: bold;font-size: 2.5em;">&pound;<%= "#{'%.2f' % (@savings / 100.0)}" %></p-->
      <p>in <%= @days %> Days</p>
    </div>

    <div id="chart" style="width: 210px; height: 160px; margin: 0 auto"></div>
  </div>

  <div id="dashboard-transactions" class="body-box">
    <%= render 'transactions/transactions_list' %>
  </div>
</div>

<script>
    $(function () {
        $('#chart').highcharts({
            chart: {
                type: 'spline'
            },
            title: {
                text: ''
            },
            subtitle: {
                //text: "How many pennies I've saved",
                x: -20
            },
            xAxis: {
                labels: {
                    enabled: false
                }
                //categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                //    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
            },
            yAxis: {
                title: {
                    text: ''
                },
                min: 0
                //plotLines: [{
                //    value: 0,
                //    width: 1,
                //    color: '#808080'
                //}]
            },
            tooltip: {
                //valueSuffix: '°C'
            },
            legend: {
                enabled: false
            },
            plotOptions: {
                spline: {
                    marker: {
                        enabled: false
                    }
                }
            },
            series: [{
                name: 'Pennies',
                data: [<%= @chart_data.join(', ') %>]
                //data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
            }]
        });
    });
</script>

app/views/dashboard/settings.html.erb
<!--h1>Settings</h1-->

<div id="user-settings">
  <form id="user-settings-form">

    <div id="active">
      <input type="radio" id="active-1" name="active" value="1" checked>
      <label id="active-1-label" for="active-1">On</label>
      <input type="radio" id="active-2" name="active" value="0" >
      <label id="active-2-label" for="active-2">Off</label>
    </div>

    <div>
      <input type="radio" id="scheme-1" name="scheme" value="1" checked>
      <label id="scheme-1-label" for="scheme-1">Round up</label>
    </div>
    <div>
      <input type="radio" id="scheme-2" name="scheme" value="2" >
      <label for="scheme-2" id="scheme-2-label">Percentage of sale</label>
    </div>
    <div>
      <input type="radio" id="scheme-3" name="scheme" value="3" >
      <label for="scheme-3" id="scheme-3-label">Fixed amount</label>
    </div>

    <div id="value-field">
      <label for="value" id="value-label">Round up to &pound;1, &pound;5 or &pound;10</label><br>
      <input type="number" value="10" min="0">
      <!--div id="value-description">
        Round your My Pennies transaction up to the nearest £1, £5 or £10.
      </div-->
    </div>
  </form>
</div>



<script type="text/javascript">

    $(function() {
        $("#active").buttonset();
    });


    $("#scheme-1").click(function() {
        $('#value-label').html('Round up to &pound;1, &pound;5 or &pound;10');
    });

    $("#scheme-1-label").click(function() {
        $('#value-label').html('Round up to &pound;1, &pound;5 or &pound;10');
    });

    $("#scheme-2-label").click(function() {
        $('#value-label').html('1% to 10%');
    });

    $("#scheme-2").click(function() {
        $('#value-label').html('1% to 10%');
    });

    $("#scheme-3-label").click(function() {
        $('#value-label').html('Number of pennies');
    });

    $("#scheme-3").click(function() {
        $('#value-label').html('Number of pennies');
    });

</script>

app/views/home/index.html.erb
<img id="logo" src="<%= image_path('logo.png') %>" >

<div class="about">
  <h2>What is this about?</h2>
  <p>An easy and swift way for you save your small change to help you build that nest egg for any special occasions & lifetime events, or to just help someone else in need by supporting a charitable cause.</p>
</div>

<div class="works">
  <h2>How does it work?</h2>
  <p>You save as you spend through your card by simply rounding up that loose change from your payment to the nearest £1, £5 or £10 and depositing it into a Savings account that meets your needs. You can even set yourself your own savings goals be and we will let you know when you reach them. </p>
</div>

<div class="Background">
  <h2>Background </h2>
  <p>UK economy is emerging from recession with consumer confidence starting to return with increases in spending. However, UK Saving habits have not improved with household savings rates dropped from 7.3% in 2012 to 4.9% in 2014. UK consumers financial resilience still remains fragile with 4/10 concerned about an unexpected expense and 1/2 concerned about their level of Savings. 1 in 4 UK households are not saving at all. Consumer spending via card purchases has continued to see an increasing trend with 75% of Retail purchases in 2014 done by Debit Card. Additional the Average Transactional Value (ATV) has decreased from £50 in 2011 to £46.75 in 2014. This has been attributed to continuing migration of low value cash payments to cards and the introduction of contactless payments which has seen greater uptake in the Retail Market.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Digital Loose Change</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://code.highcharts.com/highcharts.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div id="branding">
    <%= link_to 'Digital Loose Change', dashboard_path, id: 'logo-home-link' %>
  </div>
  <nav id="auth-links">
    <% if user_signed_in? -%>
        <span class="email"><%= current_user.email %></span> &nbsp;
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete, :confirm => 'Are you sure you want to log out?' %>
    <% else -%>
        <%#= link_to "Sign up", new_user_registration_path %>
        <%= link_to (t 'devise.fields.login'), new_user_session_path %>
    <% end -%>
  </nav>
  <nav id="section-links">
    <%= link_to 'Home', dashboard_path %> |
    <%= link_to 'Decide', decide_path %> |
    <%= link_to 'Goals', community_path %> |
    <%= link_to 'Community', community_path %> |
    <%= link_to 'Settings', settings_path %>
  </nav>
  <!--div id="flash">
    <p id="notice" class="notice"><%= notice %></p>
    <p id="alert" class="alert"><%= alert %></p>
  </div-->
</header>


<div id="body-content">
  <div id="<%= controller_name %>">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pennies Further</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <nav id="auth-links">
    <% if user_signed_in? -%>
        <span class="email"><%= current_user.email %></span> &nbsp;
        <%= link_to 'Logout', destroy_user_session_path, :method => :delete, :confirm => 'Are you sure you want to log out?' %>
    <% else -%>
        <%#= link_to "Sign up", new_user_registration_path %>
        <%= link_to (t 'devise.fields.login'), new_user_session_path %>
    <% end -%>
  </nav>
</header>

<div id="body-content">
  <div id="<%= controller_name %>">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/transactions/_form.html.erb
<%= simple_form_for(@transaction) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%#= f.collection_radio_buttons :transaction_type, [[0, 'Debit'], [1, 'Credit']], :first, :last, checked: @transaction.transaction_type %>
    <%= f.input :time %>
    <%= f.input :name %>
    <%= f.input :amount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/transactions/_transactions_list.html.erb
<div id="transactions-list">

  <div>
    <%= form_tag(dashboard_path, :method => 'get') do %>
        Transactions from &nbsp; <%= text_field_tag(:date_1, @date_1.strftime('%Y-%m-%d')) %> &nbsp; until &nbsp; <%= text_field_tag(:date_2, @date_2.strftime('%Y-%m-%d')) %>
        <%= submit_tag('Search') %>
    <% end %>
    </form>

  </div>
  <% @transactions.each do |transaction| %>
      <%
         transaction_class = ['transaction']
         transaction_class << 'debit' if transaction.debit?
         transaction_class << 'credit' if transaction.credit?
      %>
      <div class="<%= transaction_class.join(' ') %>">
        <div class="time"><%= transaction.time.strftime('%d %b %y') %></div>
        <div class="name"><%= transaction.name %></div>
        <div class="type"><%= transaction.transaction_type %></div>
        <div class="amount <%= transaction.credit? ? 'credit' : 'debit' %>"><%= "#{'%.2f' % (transaction.amount / 100.0)}" %></div>
        <% if transaction.debit_card_transaction? %>
            <div class="saving-pennies">
              <div class="time"><%#= transaction.time.strftime('%d %b %y') %></div>
              <div class="name"></div>
              <div class="type" style="font-weight: bold;">Digital Loose Change</div>
              <div class="amount <%= transaction.credit? ? 'credit' : 'debit' %>"><%= "#{'%.2f' % (transaction.saving_amount / 100.0)}" %></div>
            </div>

        <% end %>
      </div>
  <% end %>

  <script>
      $(function() {
          $("#date_1").datepicker({ dateFormat: "yy-mm-dd" });
          $("#date_2").datepicker({ dateFormat: "yy-mm-dd" });
      });
  </script>
</div>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing Transactions</h1>

<%= render 'transactions_list' %>

<%#= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @transaction.time %>
</p>

<p>
  <strong>Name:</strong>
  <%= @transaction.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @transaction.balance %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>